### ISSUE TITLE
Twitterとの新規認証ができないようです

### ISSUE THREAD

**Issue by tori-sugari** [nnsnodnb/nowplaying-ios#170]
新規にインストールをしTwitterのアカウントを追加しようとしても正しく動作しないようです。ご対応いただけますと幸いです。

**Comment by nnsnodnb** [comment]
@tori-sugari さん
ご報告ありがとうございます。
こちら手元で確認しましたところ、 Twitter アプリ経由でのログイン (`SSO`) についてログインができないというものなっていました。
現在 Twitter 社に対してアプリに対して特定の制限がかけられていないかなどの問い合わせをしており返信待ちですのでしばらくお待ちいただければ幸いです。
またこれはハードルが高いと思いますが Twitter アプリをアンインストールして NowPlaying アプリでログインをすることでアプリ内でブラウザが立ち上がり同様にログインはできることは確認できました。

ご不便をおかけしますがどうぞよろしくお願いしまします。

**Comment by tori-sugari** [comment]
nnsnodnb様
ご確認ご返信頂きありがとうございます。twitter側の問題だったのですね。とりあえずはtwitter側での対応をまちつつ、暫定回避策についても検討をさせていただきます。なおるとよいですね…！

**Comment by nnsnodnb** [comment]
こちら、 2.4.4 でアプリ内ブラウザを起動してログインするように修正いたしました。

**Comment by tori-sugari** [comment]
確認いたしました！ありがとうございます。早速愛用させていただいております。
